name: Test Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.10]  # Correct supported Python versions

    steps:

      - name: Show current directory and files
        run: ls -al

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Show the current directory
        run: pwd

      - name: List all files in the directory
        run: ls -al

      - name: List all files recursively
        run: ls -R

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest
